### ISSUE TITLE
What is the best practice for adding C++ lib to C projects?

### ISSUE THREAD

**Issue by pioneerAlone** [RaccoonlabDev/libcanard_stm32_cyphal#13]
Hello ,

I'm working on cyphal application and trying to port it to my own project (freertos + STM32). Since my project has been using pure C, I'm new to porting C++ projects. I saw your Stm3 2 The flight control project introduces the C++ environment only through the following code. Is there anything else I need to pay attention to, such as compiler options?

`
#ifdef __cplusplus
extern "C"
{
#endif

//void startup(void);

#ifdef __cplusplus
}
#endif
`

**Comment by pioneerAlone** [comment]
Will a C implementation be provided?

**Comment by PonomarevDA** [comment]
Hello.

In general, you just need to compile the library related source files with C++ compiler and link it correctly with your project.

The [Mini v2 example](https://github.com/RaccoonlabDev/mini_v2_node) is based on CMake, which automatically detects the required compiler by the file extension (g++ for .cpp and gcc for .c). I don't remember using some additional compiler options. Well, you can check them all in [CMakeLists.txt](https://github.com/RaccoonlabDev/mini_v2_node/blob/main/CMakeLists.txt).

I just wrapped the C++ code with extern "C" and explicitly specified the languages in the beginning of CMakeLists.txt:
```cmake
project(example CXX C ASM)
```

**Comment by PonomarevDA** [comment]
Is your project based on makefile, cmake or some IDE?

**Comment by pioneerAlone** [comment]
Thanks for you reply,

I've added C++ support to my project, but due to chip resource limitations (rom 64K + ram 20K), I'm worried that it is not enough to ensure good running of C++ code. It would be great if there is a minimal C implementation. But this library is a good start for me, thanks
