### ISSUE TITLE
How connect device to cyphal Yukon or Yakut

### ISSUE THREAD

**Issue by pioneerAlone** [RaccoonlabDev/libcanard_stm32_cyphal#14]
Hello ,

If I don't use "Cyphal and DroneCAN Sniffer and Programmer" HW, can I directly use a regular USB can bus tool as a bridge between my device and Cyphal Yukon or Yakut?

**Comment by PonomarevDA** [comment]
Sure. It was mainly tested with [RaccoonLab CAN-sniffer](https://docs.raccoonlab.co/guide/programmer_sniffer/), but it should work with any other CAN-USB sniffer supported by Yukon/Yakut, for example with Zubax Babel.
